# Generated by Django 5.1.1 on 2024-10-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Mahsulot nomi')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mahsulot haqida...')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Narxi')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Chegirma (%)')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('weight', models.PositiveIntegerField(verbose_name='Vazni')),
                ('made_in', models.CharField(max_length=100, verbose_name='Yetishtirilgan')),
                ('quality', models.CharField(choices=[('or', 'organic'), ('gmo', 'GMO')], max_length=3, verbose_name='Sifati')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='categories/photos/', verbose_name='Rasmi')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ('pk',),
            },
        ),
    ]
